version: "3.8"
services:
  mysqldb:
    image : mysql:5.7
    container_name: mysqldb
    volumes:
      - ./graphql_test_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graphql_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always